version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.feather

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_ADT_rates_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2015-01-01 to 2018-08-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inpu*.feather
  
  generate_ADT_rates_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2018-09-01 to 2022-08-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inp*.feather

  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs:
      [
        generate_ADT_rates_1,
        generate_ADT_rates_2,
        generate_ethnicity,
      ]
    outputs:
      highly_sensitive:
        cohort: output/measures/in*.feather
  
  generate_measures_ADT:
    run: cohortextractor:latest generate_measures --study-definition study_definition_rates --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_ADT_rates_1,
        generate_ADT_rates_2,
        join_ethnicity,
      ]
    outputs:
      moderately_sensitive:
        measure_csv1: output/measures/measure_ADT_inj*_rate.csv
        measure_csv2: output/measures/measure_ADTinjbyRegion*_rate.csv
        measure_csv3: output/measures/measure_ADTinjbyIMD*_rate.csv
        measure_csv4: output/measures/measure_ADTinjbyEthnicity*_rate.csv
        measure_csv5: output/measures/measure_ADTinjbyAge*_rate.csv
        measure_csv6: output/measures/measure_ADT_oral*_rate.csv
        measure_csv7: output/measures/measure_ADToralbyRegion*_rate.csv
        measure_csv8: output/measures/measure_ADToralbyIMD*_rate.csv
        measure_csv9: output/measures/measure_ADToralbyEthnicity*_rate.csv
        measure_csv10: output/measures/measure_ADToralbyAge*_rate.csv

  describe_trends:
    run: r:latest analysis/Descriptive_trends.R
    needs: 
      [
        generate_measures_ADT,
      ]
    outputs:
      moderately_sensitive:
        Fig1: output/ADTinj_count1.png
        Fig2: output/ADTinj_rates1.png
        Fig3: output/ADTinjbyRegion1.png
        Fig4: output/ADTinjbyIMD1.png
        Fig5: output/ADTinjbyEthnicity1.png
        Fig6: output/ADTinjbyAge1.png
        Fig7: output/ADToral_count1.png
        Fig8: output/ADToral_rates1.png
        Fig9: output/ADToralbyRegion1.png
        Fig10: output/ADToralbyIMD1.png
        Fig11: output/ADToralbyEthnicity1.png
        Fig12: output/ADToralbyAge1.png