version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.feather

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_ADT_rates_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2015-01-01 to 2019-06-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inpu*.feather
  
  generate_ADT_rates_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2019-07-01 to 2024-05-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inp*.feather

  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs:
      [
        generate_ADT_rates_1,
        generate_ADT_rates_2,
        generate_ethnicity,
      ]
    outputs:
      highly_sensitive:
        cohort: output/measures/in*.feather
  
  generate_measures_ADT:
    run: cohortextractor:latest generate_measures --study-definition study_definition_rates --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_ADT_rates_1,
        generate_ADT_rates_2,
        join_ethnicity,
      ]
    outputs:
      moderately_sensitive:
        measure_csv1: output/measures/measure_ADT_inj*_rate.csv
        measure_csv2: output/measures/measure_ADT_inj1*_rate.csv
        measure_csv3: output/measures/measure_ADT_inj3*_rate.csv
        measure_csv4: output/measures/measure_ADT_inj6*_rate.csv
        measure_csv5: output/measures/measure_ADTinjbyIMD*_rate.csv
        measure_csv6: output/measures/measure_ADTinjbyEthnicity*_rate.csv
        measure_csv7: output/measures/measure_ADTinjbyAge*_rate.csv
        measure_csv8: output/measures/measure_ADTinj1byIMD*_rate.csv
        measure_csv9: output/measures/measure_ADTinj1byEthnicity*_rate.csv
        measure_csv10: output/measures/measure_ADTinj1byAge*_rate.csv
        measure_csv11: output/measures/measure_ADTinj3byIMD*_rate.csv
        measure_csv12: output/measures/measure_ADTinj3byEthnicity*_rate.csv
        measure_csv13: output/measures/measure_ADTinj3byAge*_rate.csv
        measure_csv14: output/measures/measure_ADTinj6byIMD*_rate.csv
        measure_csv15: output/measures/measure_ADTinj6byEthnicity*_rate.csv
        measure_csv16: output/measures/measure_ADTinj6byAge*_rate.csv

  describe_trends:
    run: r:latest analysis/Descriptive_trends.R
    needs: 
      [
        generate_measures_ADT,
        generate_study_population
      ]
    outputs:
      moderately_sensitive:
        fig1: output/ADT_inj_rat.png
        fig2: output/ADT_inj1_ra.png
        fig3: output/ADT_inj3_ra.png
        fig4: output/ADT_inj6_ra.png
        fig5: output/ADTinjbyIMD_.png
        fig6: output/ADTinjbyEthn.png
        fig7: output/ADTinjbyAge_.png
        fig8: output/ADTinj1byIMD.png
        fig9: output/ADTinj1byEth.png
        fig10: output/ADTinj1byAge.png
        fig11: output/ADTinj3byIMD.png
        fig12: output/ADTinj3byEth.png
        fig13: output/ADTinj3byAge.png
        fig14: output/ADTinj6byIMD.png
        fig15: output/ADTinj6byEth.png
        fig16: output/ADTinj6byAge.png     
        csv1: output/ADT_inj_rat_rounded.csv
        csv2: output/ADT_inj1_ra_rounded.csv
        csv3: output/ADT_inj3_ra_rounded.csv
        csv4: output/ADT_inj6_ra_rounded.csv
        csv5: output/ADTinjbyIMD__rounded.csv
        csv6: output/ADTinjbyEthn_rounded.csv
        csv7: output/ADTinjbyAge__rounded.csv
        csv8: output/ADTinj1byIMD_rounded.csv
        csv9: output/ADTinj1byEth_rounded.csv
        csv10: output/ADTinj1byAge_rounded.csv
        csv11: output/ADTinj3byIMD_rounded.csv
        csv12: output/ADTinj3byEth_rounded.csv
        csv13: output/ADTinj3byAge_rounded.csv       
        csv14: output/ADTinj6byIMD_rounded.csv
        csv15: output/ADTinj6byEth_rounded.csv
        csv16: output/ADTinj6byAge_rounded.csv
        csv17: output/Table1.csv
